config/routes.rb
Rails.application.routes.draw do
  root 'subs#index'

  resources :departments do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def index
    @departments = Department.all
  end
  
  def show
    @department = Department.find(params[:id])
  end
  
  def new
    @department = Department.new
  end
  
  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end
  
  def edit
    @department = Department.find(params[:id])
  end
  
  def update
    @department = Department.find(params[:id])
    
    if @department.update(department_params)
      redirect_to departments_path
    else
      render :edit
    end
  end
  
  def destroy
    Department.find(params[:id]).destroy
    redirect_to departments_path
  end

  private
  def department_params
   params.require(:department).permit(:name)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_departments
  before_action: set_item, only [:show, :edit, :update, :destroy]

  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @item = @department.items.new(item_params)

    if @item.save
      redirect_to [@department, @item]
    else
    render :new
    end
  end

  def update 
    if @item.update(item_params)
      redirect_to [@department, @item]
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path(@department)
  end

  private
    def set_department
      @department = Department.find(params[:department_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :price, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
def new
  @department = Department.new
  render partial: "form"
end

def edit
  render partial: "form"
end

app/views/departments/edit.html.erb
<h1>Edit Department</h1>
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
<br />
  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1> Departments </h1>
<p> <%= link_to "New Department", new_department_path %> </p>
<hr />

<% @departments.each do |department| %>
  <p> <%= department.name %> </p>
  <p> <%= link_to "Edit Department", edit_department_path(department.id) %> </p>
  <p> <%= link_to "View Department", department %> </p>
  <p> <%= link_to "Burn This Department Down", department, method: :delete %> </p>

<% end %>

app/views/departments/new.html.erb
<h1> New Department </h1>
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.submit %>
<% end %>

app/views/departments/show.html.erb
<h1> <%= @department.name %> </h1>
<%= link_to "Back", departments_path %>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :price %>
  <%= f.text_field :price %>
  <br />
  <%= f.label :description%>
  <%= f.text_area :description %>
  <br/ >
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>View Items</h1>
<%= link_to 'List a New Item', new_department_item_path(@department) %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, [@department, @item] %></li>
  <% end %>
</ul>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1> <%= @department.name %> - <%= @item.name %> </h1>
<p> <%= @item.description %> </p>
<%= link_to 'Edit item', edit_department_item_path([@description, @item]) %>
<%= link_to 'Burn This Item', [@description, @item], method: :delete %>
<%= link_to 'Back To Items', department_items_path(@department) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepStoreApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    <%= yield %>
  </body>
</html>